### ISSUE TITLE
Not clear how to enable/disable specific warnings

### ISSUE THREAD

**Issue by eyalroz** [Lectem/cpp-boilerplate#13]
I'm looking at the file [`Warnings.cmake`](https://github.com/Lectem/cpp-boilerplate/blob/master/cmake/Warnings.cmake). From the syntax of the `target_set_warnings()` function it defines, it seems  to allow you to disable or enable specific warnings, not just `ALL` or `Annoying`; yet - I can't see where in the code this is handled. It seems like it isn't.

Am I missing something? Is this intentional?

**Comment by Lectem** [comment]
This is indeed a mistake!
I have to admit I never had the need to disable or enable specific warnings since I tend to just update the ones blacklisted as annoying, and so entirely forgot to implement it. Note that in general, I think that disabling warnings for specific files is better handled using pragma, see https://github.com/Lectem/Worldstone/blob/master/source/system/include/Platform.h#L88. 

This is however a big missing feature, since one might need/want to disable specific warnings for a given target known to hav  issues, so I will update the script as soon as I can.

**Comment by eyalroz** [comment]
Actually, I think it's more important to be able to _enable_ specific warnings which are not enabled by default, not even with `-Wextra`. See @lefticus' [list](https://github.com/lefticus/cpp_starter_project/blob/master/CMakeLists.txt) in his [cpp_starter_project[https://github.com/lefticus/cpp_starter_project).

**Comment by Lectem** [comment]
Since we I use `-Weverything` on clang, maybe I should add those warnings when setting them to ALL ?
I'll try to find some time this week-end to make sure enable/disable works properly.
The only thing that bothers me is the API, should I let the user do the "if(COMPILER) add compiler specific warning" or should I provide a way to specify warnings per compiler with functions that do nothing if they are not compatible with the current compiler ?

**Comment by eyalroz** [comment]
> maybe I should add those warnings when setting them to ALL ?

@Lectem : I'm not sure. Not everyone would appreciate these. Perhaps it's too much.

> The only thing that bothers me is the API, should I let the user do the "if(COMPILER) add compiler specific warning" or should I provide a way to specify warnings per compiler with functions that do nothing if they are not compatible with the current compiler ?

This is actually a general CMake problem with C++ compilers - there's no canonical mechanism for disabling and enabling errors and warnings over different compilers. I don't think it should be up to you to implement one - it's a whole lot of work. To be honest, I'm not quite sure what to suggest.  I suppose the specifying (compiler, warning) pairs for disabling or enabling would at least be practicable, even if inelegant.

**Comment by Lectem** [comment]
Sorry it took so long, was pretty busy.
What do you think of #14 ?

**Comment by eyalroz** [comment]
@Lectem : The example there is not clear enough. Can you make it more concrete/specific? Otherwise - if it works, it works I guess.

**Comment by Lectem** [comment]
I updated the example !
