### ISSUE TITLE
So How to build the project?

### ISSUE THREAD

**Issue by shelper** [Lectem/cpp-boilerplate#15]
it is not clear if this project boiler plate is buildable?
if so, how to build it?
Maybe put into readme /FAQ

**Comment by Lectem** [comment]
Ah right, I just assumed people were familiar enough with cmake, I'll add a few instructions for that.
The issue is that it depends mainly on the platform you are running on.

```
mkdir build
cd builld
cmake ..
cmake --build . 
```
First line creates the build folder, second sets the current directory to it.
third will generate the files for your default build system. (this can be done easily for configuration with cmake-gui) 
fourth will actually do the build but can be replaced by the commands of your buildsystem(make, ninja, open the visual studio solution)
